#include <stdio.h>
#include "dashboard_html.h"

static const char *s_html =
"<!DOCTYPE html>"
"<html lang=\"zh-CN\">"
"<head>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
"<meta name=\"color-scheme\" content=\"dark\">"
"<title>看门狗控制台 · ESP32-C3</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",\"Microsoft YaHei\",sans-serif;"
"background:radial-gradient(circle at 15% -10%,#2e1065 0,transparent 45%),"
"radial-gradient(circle at 85% 110%,#0c2d48 0,transparent 45%),#0b1220;"
"color:#e2e8f0;min-height:100vh;padding:18px 20px 50px}"
".wrap{max-width:1080px;margin:0 auto}"
"/* ===== 顶栏 ===== */"
".topbar{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px;flex-wrap:wrap;gap:12px}"
".brand{display:flex;align-items:center;gap:13px}"
".logo{width:44px;height:44px;border-radius:12px;background:linear-gradient(135deg,#38bdf8,#4f6ef7);"
"display:flex;align-items:center;justify-content:center;font-weight:800;font-size:22px;color:#0b1220;"
"box-shadow:0 6px 18px rgba(79,110,247,.45)}"
".brand h1{font-size:19px;color:#f1f5f9;letter-spacing:.5px}"
".brand .ver{font-size:12px;color:#64748b;margin-top:2px}"
".topright{display:flex;align-items:center;gap:10px;flex-wrap:wrap}"
".uptime{background:rgba(255,255,255,.05);padding:7px 13px;border-radius:20px;border:1px solid rgba(255,255,255,.08);"
"font-size:12px;color:#94a3b8;font-family:ui-monospace,Menlo,Consolas,monospace}"
".btn-top{color:#cbd5e1;text-decoration:none;padding:8px 16px;border-radius:9px;font-size:13px;cursor:pointer;border:none;"
"background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.1);transition:.2s;font-family:inherit}"
".btn-top:hover{color:#fff;background:rgba(255,255,255,.12)}"
".btn-top.danger:hover{color:#fff;background:rgba(239,68,68,.3);border-color:#ef4444}"
"/* ===== 三列布局 ===== */"
".cols{display:grid;grid-template-columns:1.15fr 1fr 1fr;gap:16px;margin-bottom:16px;align-items:stretch}"
".col{display:flex;flex-direction:column;gap:16px}"
".col .card{margin:0}"
".card.grow{flex:1;display:flex;flex-direction:column;align-items:stretch}"
"@media(max-width:900px){.cols{grid-template-columns:1fr}.card.grow{flex:none}}"
".card{background:rgba(30,41,59,.72);backdrop-filter:blur(12px);border:1px solid rgba(255,255,255,.08);"
"border-radius:16px;padding:20px}"
".card h2{font-size:14px;color:#94a3b8;font-weight:600;margin-bottom:15px;display:flex;align-items:center;gap:8px;letter-spacing:.5px}"
".card h2 .bar{width:4px;height:16px;border-radius:3px;background:#38bdf8;flex:none}"
".card h2 .tag{margin-left:auto;font-size:11px;color:#64748b;font-weight:400;background:rgba(255,255,255,.05);"
"padding:3px 9px;border-radius:6px}"
"/* ===== 服务器状态 ===== */"
".status{display:flex;align-items:center;gap:20px}"
".led{width:88px;height:88px;border-radius:50%;background:#64748b;flex-shrink:0;"
"box-shadow:0 0 0 8px rgba(100,116,139,.12),0 0 40px rgba(100,116,139,.35);transition:all .6s}"
".led.pulse{animation:pulse 2s infinite}"
"@keyframes pulse{0%{box-shadow:0 0 0 0 rgba(34,197,94,.45)}70%{box-shadow:0 0 0 16px rgba(34,197,94,0)}100%{box-shadow:0 0 0 0 rgba(34,197,94,0)}}"
".state{font-size:22px;font-weight:800;color:#64748b;transition:color .4s;line-height:1.3}"
".subinfo{margin-top:11px;display:flex;flex-direction:column;gap:6px;font-size:13px;color:#94a3b8}"
".subinfo span{display:flex;align-items:center;gap:8px}"
".dot{width:8px;height:8px;border-radius:50%;background:#64748b;display:inline-block;flex:none}"
"/* ===== 统计 ===== */"
".stats{display:grid;grid-template-columns:1fr 1fr;gap:10px}"
".stat{background:rgba(15,23,42,.6);border:1px solid rgba(255,255,255,.06);border-radius:12px;padding:13px 14px}"
".stat .label{font-size:11px;color:#64748b;margin-bottom:5px}"
".stat .value{font-size:25px;font-weight:800;color:#38bdf8}"
".stat .value small{font-size:12px;color:#64748b;font-weight:500;margin-left:3px}"
".stat.full{grid-column:1/-1}"
"/* ===== 表单 ===== */"
"label{display:block;font-size:12px;color:#94a3b8;margin:11px 0 6px}"
"label:first-of-type{margin-top:0}"
"input{width:100%;padding:11px 12px;border:1px solid #334155;border-radius:9px;background:#0f172a;color:#e2e8f0;"
"font-size:14px;transition:border .2s}"
"input:focus{outline:none;border-color:#38bdf8}"
"input[type=checkbox]{width:18px;height:18px;flex:none;margin-top:1px}"
"/* ===== 拨动开关 (iOS 风格, 复用 checkbox 的 checked 状态) ===== */"
"input.switch{appearance:none;-webkit-appearance:none;width:44px;height:24px;border-radius:12px;"
"background:#334155;position:relative;cursor:pointer;transition:background .25s;flex:none;margin:0;border:none}"
"input.switch:before{content:'';position:absolute;top:3px;left:3px;width:18px;height:18px;border-radius:50%;"
"background:#fff;box-shadow:0 1px 3px rgba(0,0,0,.4);transition:transform .25s}"
"input.switch:checked{background:#0a84ff}"
"input.switch:checked:before{transform:translateX(20px)}"
"input.switch:focus-visible{outline:2px solid #38bdf8;outline-offset:2px}"
"/* ===== 按钮 ===== */"
".btn{padding:11px 22px;border:none;border-radius:9px;font-size:14px;font-weight:700;cursor:pointer;"
"transition:transform .1s,opacity .2s,filter .2s;font-family:inherit}"
".btn:active{transform:scale(.98)}"
".btn:disabled{opacity:.45;cursor:not-allowed;filter:grayscale(.5)}"
".btn-block{display:block;width:100%;margin-top:10px}"
".btn-block:first-of-type{margin-top:14px}"
".btn-primary{background:linear-gradient(135deg,#38bdf8,#0ea5e9);color:#0b1220}"
".btn-power{background:linear-gradient(135deg,#22c55e,#16a34a);color:#fff}"
".btn-danger{background:linear-gradient(135deg,#ef4444,#dc2626);color:#fff}"
".btn-secondary{background:#3b4a63;color:#e2e8f0}"
".btn-secondary:hover{background:#334155}"
".row2{display:flex;flex-wrap:wrap;gap:10px}"
"/* ===== OTA 上传 ===== */"
".drop{border:2px dashed #334155;border-radius:12px;padding:14px 12px;text-align:center;cursor:pointer;"
"transition:all .25s;position:relative;background:rgba(15,23,42,.4)}"
".drop:hover,.drop.drag{border-color:#38bdf8;background:rgba(56,189,248,.07)}"
".drop.hasfile{border-color:#22c55e;border-style:solid;background:rgba(34,197,94,.07)}"
".drop p{color:#94a3b8;font-size:12.5px;line-height:1.6}"
".drop .file{color:#38bdf8;font-weight:600}"
".drop input[type=file]{position:absolute;inset:0;opacity:0;cursor:pointer}"
".meta{display:flex;gap:8px;margin-top:12px}"
".meta div{flex:1;background:rgba(15,23,42,.6);border:1px solid rgba(255,255,255,.06);border-radius:9px;padding:8px 10px;min-width:0}"
".meta .k{font-size:10px;color:#64748b}"
".meta .v{font-size:13px;font-weight:700;color:#e2e8f0;margin-top:2px;word-break:break-all}"
".progress{height:9px;background:#0f172a;border-radius:6px;margin-top:12px;overflow:hidden;display:none}"
".progress .bar{height:100%;width:0;background:linear-gradient(90deg,#38bdf8,#6366f1);transition:width .3s}"
".hint{font-size:12px;color:#64748b;margin-top:11px;line-height:1.7}"
"/* 悬停提示气泡: 鼠标指向\"推送格式说明\"时弹出, 不占版面 */"
".tipbox{position:relative;display:inline-block;margin-top:11px}"
".tip-trigger{cursor:help;font-size:12px;color:#64748b;border-bottom:1px dashed #475569}"
".tipbox:hover .tip-trigger,.tipbox:focus-within .tip-trigger{color:#94a3b8}"
".tip-body{position:absolute;left:0;bottom:calc(100% + 9px);width:290px;max-width:76vw;padding:10px 12px;"
"background:#0f172a;border:1px solid rgba(255,255,255,.14);border-radius:10px;color:#cbd5e1;"
"font-size:12px;line-height:1.7;box-shadow:0 14px 34px rgba(0,0,0,.55);z-index:60;"
"visibility:hidden;opacity:0;transition:opacity .2s;pointer-events:none}"
".tipbox:hover .tip-body,.tipbox:focus-within .tip-body{visibility:visible;opacity:1}"
".tip-body:after{content:'';position:absolute;top:100%;left:18px;border:6px solid transparent;border-top-color:#0f172a}"
"/* 行内数字框 (如\"连续 N 次\") */"
"input.inline-num{width:62px;padding:3px 6px;margin:0 5px;text-align:center;display:inline-block;vertical-align:middle}"
"/* ===== 电源状态 ===== */"
".power{display:flex;align-items:center;gap:10px;font-size:22px;font-weight:800;color:#64748b}"
".power .pdot{width:12px;height:12px;border-radius:50%;background:#64748b;flex:none;transition:.3s}"
"/* ===== 日志 ===== */"
"/* 日志框固定高度 (约 12 行), 更多日志在框内滚动查看 */"
".log{max-height:252px;overflow-y:auto;font-family:'SF Mono',Consolas,monospace;font-size:12px;"
"background:rgba(15,23,42,.7);border-radius:11px;padding:12px;border:1px solid rgba(255,255,255,.06)}"
".log div{padding:2px 0;color:#cbd5e1;border-bottom:1px solid rgba(255,255,255,.04)}"
".log .l-warn{color:#f59e0b}.log .l-error{color:#ef4444}.log .l-info{color:#38bdf8}"
".log::-webkit-scrollbar{width:6px}"
".log::-webkit-scrollbar-thumb{background:#334155;border-radius:3px}"
"/* ===== Toast ===== */"
"#toast{position:fixed;bottom:24px;left:50%;transform:translateX(-50%) translateY(24px);"
"background:#22c55e;color:#fff;padding:14px 26px;border-radius:12px;font-size:14px;font-weight:600;"
"opacity:0;transition:all .35s;z-index:999;box-shadow:0 12px 40px rgba(0,0,0,.35);max-width:90%;text-align:center}"
"#toast.active{opacity:1;transform:translateX(-50%) translateY(0)}"
"#toast.error{background:#ef4444}"
"#toast.warn{background:#f59e0b;color:#0b1220}"
".ok{color:#22c55e}.err{color:#ef4444}"
"@media(max-width:520px){.stats{grid-template-columns:1fr}.meta{flex-direction:column}}"
"</style>"
"</head>"
"<body>"
"<div class=\"wrap\">"
"<!-- 顶栏 -->"
"<div class=\"topbar\">"
"<div class=\"brand\">"
"<div class=\"logo\">W</div>"
"<div>"
"<h1>看门狗控制台</h1>"
"<div class=\"ver\">版本 v{{VERSION}} · 编译日期 {{BUILD_DATE}}</div>"
"</div>"
"</div>"
"<div class=\"topright\">"
"<button class=\"btn-top danger\" onclick=\"resetWifi()\">恢复出厂设置</button>"
"<span class=\"uptime\" id=\"uptime\">运行中...</span>"
"<a class=\"btn-top\" href=\"/logout\">退出</a>"
"</div>"
"</div>"
"<!-- 三列卡片 -->"
"<div class=\"cols\">"
"<!-- 第 1 列: 服务器状态 + 看门狗参数 -->"
"<div class=\"col\">"
"<div class=\"card\">"
"<h2><span class=\"bar\"></span>服务器状态</h2>"
"<div class=\"status\">"
"<div class=\"led {{LED_CLASS}}\" id=\"led\" style=\"background:{{LED_COLOR}}\"></div>"
"<div>"
"<div class=\"state\" id=\"state\">{{STATE_TEXT}}</div>"
"<div class=\"subinfo\">"
"<span><i class=\"dot\" id=\"usbDot\"></i> USB CDC: <b id=\"usbTxt\">{{USB_STATE}}</b></span>"
"<span><i class=\"dot\"></i> 心跳间隔: <b>{{INTERVAL}} s</b> · 超时: <b>{{TIMEOUT}} s</b></span>"
"<span><i class=\"dot\"></i> IP: <b id=\"ipTxt\">获取中</b> · 信号: <b id=\"rssiTxt\">-</b></span>"
"<span><i class=\"dot\"></i> 分区: <b>{{PARTITION}}</b></span>"
"</div>"
"</div>"
"</div>"
"</div>"
"<div class=\"card grow\">"
"<h2><span class=\"bar\"></span>看门狗参数</h2>"
"<label>心跳间隔 (秒) — 每 N 秒发送一次</label>"
"<input type=\"number\" id=\"interval\" value=\"{{INTERVAL}}\" min=\"1\" max=\"3600\" title=\"1~3600 秒\">"
"<label>超时时间 (秒) — 超过则判定服务器宕机</label>"
"<input type=\"number\" id=\"timeout\" value=\"{{TIMEOUT}}\" min=\"60\" max=\"86400\" title=\"60~86400 秒, 且必须 ≥ 2×间隔\">"
"<label style=\"margin-top:16px\">自动保护</label>"
"<label style=\"display:flex;align-items:center;gap:10px;margin-top:2px;cursor:pointer\">"
"<input type=\"checkbox\" class=\"switch\" id=\"poweroffEnabled\" {{POWEROFF_STATE}}>"
"<span>连续 <input type=\"number\" class=\"inline-num\" id=\"poweroffCnt\" value=\"{{POWEROFF_CNT}}\" min=\"1\" max=\"20\" title=\"1~20 次\"> 次重启未恢复 → 自动强制关机</span>"
"</label>"
"<div style=\"margin-top:auto;padding-top:14px\">"
"<button class=\"btn btn-primary btn-block\" onclick=\"saveSettings()\">保存设置</button>"
"</div>"
"</div>"
"<!-- 实时事件日志 -->"
"<div class=\"card\">"
"<h2><span class=\"bar\"></span>实时事件日志<button class=\"tag\" style=\"cursor:pointer;border:none;font-family:inherit\" onclick=\"clearLogs()\">清空日志</button></h2>"
"<div class=\"log\" id=\"log\">加载中...</div>"
"</div>"
"</div>"
"<!-- 第 2 列: 心跳统计 + 电源控制 -->"
"<div class=\"col\">"
"<div class=\"card\">"
"<h2><span class=\"bar\"></span>心跳统计<button class=\"tag\" style=\"cursor:pointer;border:none;font-family:inherit\" onclick=\"resetStats()\">清零</button></h2>"
"<div class=\"stats\">"
"<div class=\"stat\"><div class=\"label\">心跳数</div><div class=\"value\">{{HB_COUNT}}<small>次</small></div></div>"
"<div class=\"stat\"><div class=\"label\">响应数</div><div class=\"value\">{{RESP_COUNT}}<small>次</small></div></div>"
"<div class=\"stat\"><div class=\"label\">超时数</div><div class=\"value\">{{TIMEOUT_COUNT}}<small>次</small></div></div>"
"<div class=\"stat\"><div class=\"label\">服务器已重启</div><div class=\"value\">{{REBOOT_COUNT}}<small>次</small></div></div>"
"<div class=\"stat full\"><div class=\"label\">连续重启 (自动保护计数)</div><div class=\"value\" id=\"consecReboots\">{{CONSEC_REBOOTS}}<small>次</small></div></div>"
"</div>"
"</div>"
"<div class=\"card grow\">"
"<h2><span class=\"bar\"></span>服务器电源控制</h2>"
"<button class=\"btn btn-power btn-block\" id=\"powerBtn\" style=\"margin-top:auto\" onclick=\"powerToggle()\">⏻ 开机（关机）</button>"
"<button class=\"btn btn-danger btn-block\" style=\"margin-top:10px\" onclick=\"rebootServer()\">🅾 重启服务器</button>"
"<button class=\"btn btn-danger btn-block\" style=\"margin-top:10px\" onclick=\"powerOffServer()\">⏹ 强制关机</button>"
"</div>"
"<!-- 消息通知 -->"
"<div class=\"card\">"
"<h2><span class=\"bar\"></span>消息通知</h2>"
"<label style=\"display:flex;align-items:flex-start;gap:10px;margin-top:0;cursor:pointer\">"
"<input type=\"checkbox\" class=\"switch\" id=\"notifyEnabled\" {{NOTIFY_STATE}}>"
"<span>推送通知</span>"
"</label>"
"<label>通知服务地址 (Base URL)</label>"
"<input type=\"text\" id=\"notifyUrl\" value=\"{{NOTIFY_URL}}\" maxlength=\"192\" placeholder=\"https://你的域名\">"
"<label>鉴权令牌 (可留空)</label>"
"<input type=\"password\" id=\"notifyToken\" value=\"{{NOTIFY_TOKEN}}\" maxlength=\"96\" placeholder=\"Bearer 令牌\" autocomplete=\"new-password\">"
"<div class=\"tipbox\" tabindex=\"0\">"
"<span class=\"tip-trigger\">推送格式说明</span>"
"<div class=\"tip-body\">"
"POST &lt;地址&gt;/n · 头 <b>Authorization: Bearer &lt;令牌&gt;</b><br>"
"体 <b>{\"t\":\"标题\",\"m\":\"内容\",\"k\":\"令牌\",\"event\":\"...\",\"ts\":123}</b><br>"
"event: server_down 宕机 / force_poweroff 强制关机 / watchdog_stopped 看门狗停止 / power_on 开机 / test 测试"
"</div>"
"</div>"
"<div class=\"row2\" style=\"margin-top:12px\">"
"<button class=\"btn btn-primary\" style=\"flex:1;min-width:104px\" onclick=\"saveProtect()\">保存设置</button>"
"<button class=\"btn btn-secondary\" style=\"flex:1;min-width:104px\" onclick=\"testNotify()\">测试通知</button>"
"</div>"
"</div>"
"</div>"
"<!-- 第 3 列: 电源状态 + 登录凭据 + 固件升级 -->"
"<div class=\"col\">"
"<div class=\"card\">"
"<h2><span class=\"bar\"></span>服务器电源状态</h2>"
"<div class=\"power\"><span class=\"pdot\" id=\"powerDot\"></span><span id=\"powerState\">检测中...</span></div>"
"<div class=\"hint\" id=\"powerHint\">通过 PWR_LED (GPIO7) 检测，每 3 秒刷新</div>"
"</div>"
"<div class=\"card\">"
"<h2><span class=\"bar\"></span>登录凭据</h2>"
"<label>新用户名 (留空则不修改)</label>"
"<input type=\"text\" id=\"username\" placeholder=\"admin\">"
"<label>当前密码 <span class=\"err\">*</span></label>"
"<input type=\"password\" id=\"old_password\" placeholder=\"验证身份\">"
"<label>新密码 (至少 4 位)</label>"
"<input type=\"password\" id=\"password\" placeholder=\"••••••••\">"
"<button class=\"btn btn-primary btn-block\" onclick=\"changePassword()\">更新用户名 / 密码</button>"
"</div>"
"<div class=\"card grow\">"
"<h2><span class=\"bar\"></span>固件升级 (OTA)<span class=\"tag\" id=\"otaTag\">空闲</span></h2>"
"<div class=\"drop\" id=\"drop\">"
"<p>拖拽 .bin 固件到此处，或 <span class=\"file\">点击选择文件</span></p>"
"<input type=\"file\" id=\"firmware\" accept=\".bin,.hex,application/octet-stream\">"
"</div>"
"<div class=\"meta\" id=\"meta\" style=\"display:none\">"
"<div><div class=\"k\">文件名</div><div class=\"v\" id=\"mName\">-</div></div>"
"<div><div class=\"k\">大小</div><div class=\"v\" id=\"mSize\">-</div></div>"
"<div><div class=\"k\">固件版本</div><div class=\"v\" id=\"mVer\">上传后解析</div></div>"
"</div>"
"<div class=\"progress\" id=\"progress\"><div class=\"bar\" id=\"bar\"></div></div>"
"<div class=\"hint\" id=\"otaCheck\">当前固件 v{{VERSION}}</div>"
"<div class=\"row2\" style=\"margin-top:10px\">"
"<button class=\"btn btn-secondary\" style=\"flex:1;min-width:104px\" id=\"checkBtn\" onclick=\"checkUpdate()\">检查更新</button>"
"<button class=\"btn btn-primary\" style=\"flex:1;min-width:104px\" id=\"uploadBtn\" onclick=\"uploadFirmware()\" disabled>上传并刷写固件</button>"
"</div>"
"<div class=\"hint\">升级期间请勿断电；新固件启动失败将自动回滚上一版本。</div>"
"<button class=\"btn btn-secondary btn-block\" id=\"rebootBtn\" onclick=\"rebootDevice()\" style=\"display:none\">立即重启设备</button>"
"</div>"
"</div>"
"</div>"
"</div>"
"<div id=\"toast\"></div>"
"<script>"
"var selectedFile=null,otaDone=false;"
"function showToast(msg,type){"
"var t=document.getElementById('toast');"
"t.textContent=msg;t.className=(type==='error'?'active error':type==='warn'?'active warn':'active');"
"setTimeout(function(){t.className='';},4000);"
"}"
"/* ===== OTA: 文件选择 ===== */"
"var drop=document.getElementById('drop'),fi=document.getElementById('firmware'),"
"up=document.getElementById('uploadBtn'),meta=document.getElementById('meta');"
"function pickFile(file){"
"selectedFile=file;"
"if(!file)return;"
"if(!/\\.bin$/i.test(file.name)&&file.type!=='application/octet-stream'){"
"showToast('请选择 .bin 固件文件','error');selectedFile=null;return;"
"}"
"var kb=Math.round(file.size/1024);"
"drop.querySelector('p').innerHTML='已选择: <span class=\"file\">'+file.name+'</span> ('+kb+' KB)';"
"drop.classList.add('hasfile');"
"meta.style.display='flex';"
"document.getElementById('mName').textContent=file.name;"
"document.getElementById('mSize').textContent=kb+' KB';"
"document.getElementById('mVer').textContent='待校验';"
"up.disabled=false;"
"}"
"fi.addEventListener('change',function(e){pickFile(e.target.files[0]);});"
"['dragenter','dragover'].forEach(function(ev){drop.addEventListener(ev,function(e){e.preventDefault();drop.classList.add('drag');});});"
"['dragleave','drop'].forEach(function(ev){drop.addEventListener(ev,function(e){e.preventDefault();drop.classList.remove('drag');});});"
"drop.addEventListener('drop',function(e){if(e.dataTransfer.files.length)pickFile(e.dataTransfer.files[0]);});"
"/* 解析上传镜像中的固件版本 (esp_app_desc_t 在镜像头部固定偏移) */"
"function readVersion(file){"
"var slice=file.slice(0,2048);var fr=new FileReader();"
"fr.onload=function(e){"
"var b=new Uint8Array(e.target.result);"
"var el=document.getElementById('mVer');"
"/* ESP32 镜像头 (24 字节, v4.3+) + 第1段头 (8 字节) => esp_app_desc 自偏移 32 起 */"
"if(b.length<80||b[0]!==0xe9){el.textContent='非标准镜像';return;}"
"/* esp_app_desc_t: magic_word(4)=0xABCD5432 @32, version[32]@+16 (即镜像偏移 48) */"
"var dm=(b[32]|(b[33]<<8)|(b[34]<<16)|(b[35]<<24))>>>0;"
"if(dm!==0xABCD5432){el.textContent='未知 (无应用描述)';return;}"
"var v='';for(var i=48;i<80&&b[i];i++)v+=String.fromCharCode(b[i]);"
"el.textContent=v||'未知';"
"};"
"fr.readAsArrayBuffer(slice);"
"}"
"fi.addEventListener('change',function(e){if(e.target.files[0])readVersion(e.target.files[0]);});"
"/* ===== OTA: 上传 (XHR + 进度) ===== */"
"function uploadFirmware(){"
"if(!selectedFile){showToast('请先选择固件文件','warn');return;}"
"if(!confirm('确定刷写固件吗？过程请勿断电。'))return;"
"var xhr=new XMLHttpRequest();"
"xhr.open('POST','/api/firmware');"
"xhr.setRequestHeader('Content-Type','application/octet-stream');"
"var prog=document.getElementById('progress'),bar=document.getElementById('bar'),tag=document.getElementById('otaTag');"
"prog.style.display='block';up.disabled=true;otaDone=false;"
"tag.textContent='上传中';tag.style.color='#38bdf8';"
"xhr.upload.onprogress=function(e){if(e.lengthComputable){var p=Math.round(e.loaded*100/e.total);bar.style.width=p+'%';}};"
"xhr.onload=function(){"
"try{var resp=JSON.parse(xhr.responseText);"
"if(resp.status==='ok'){"
"bar.style.width='100%';tag.textContent='写入中';tag.style.color='#f59e0b';"
"showToast('文件已上传，正在写入 Flash...', '');"
"pollOtaStatus();"
"}else{"
"tag.textContent='失败';tag.style.color='#ef4444';"
"showToast((resp.message||'刷写失败')+' (code '+(resp.code||'')+')','error');up.disabled=false;"
"}"
"}catch(err){showToast('服务器无响应，可能正在重启', '');setTimeout(function(){location.reload();},3000);}"
"};"
"function pollOtaStatus(){"
"var timer=setInterval(function(){"
"fetch('/api/ota/status').then(function(r){return r.json();}).then(function(s){"
"if(s.state==='writing'){bar.style.width=s.progress+'%';}"
"else if(s.state==='success'){"
"otaDone=true;clearInterval(timer);bar.style.width='100%';"
"tag.textContent='成功 · 待重启';tag.style.color='#22c55e';"
"showToast('刷写成功，设备即将重启 (约 3 秒)...', '');"
"document.getElementById('rebootBtn').style.display='block';"
"setTimeout(function(){location.reload();},4000);"
"}else if(s.state==='failed'){"
"otaDone=true;clearInterval(timer);tag.textContent='失败';tag.style.color='#ef4444';"
"showToast('写入失败，请重试','error');up.disabled=false;"
"}"
"}).catch(function(){if(!otaDone){clearInterval(timer);setTimeout(pollOtaStatus,1500);}});"
"},1000);"
"}"
"xhr.onerror=function(){showToast('网络错误，请重试','error');up.disabled=false;};"
"xhr.send(selectedFile);"
"}"
"function rebootDevice(){if(confirm('立即重启看门狗设备？服务器不受影响。'))fetch('/api/device_reboot',{method:'POST'}).then(function(r){return r.json();}).then(function(d){showToast(d.message||'设备重启中');}).catch(function(){setTimeout(function(){location.reload();},3000);});}"
"/* ===== 在线检查新固件 ===== */"
"/* 点\"检查更新\" -> POST /api/ota/check 立即返回, 结果轮询 /api/ota/status 取 */"
"function checkUpdate(){"
"var btn=document.getElementById('checkBtn'),el=document.getElementById('otaCheck'),tag=document.getElementById('otaTag');"
"if(btn.disabled)return;"
"btn.disabled=true;el.textContent='正在检查更新...';"
"fetch('/api/ota/check',{method:'POST'}).then(function(r){return r.json();}).then(function(d){"
"if(d.status!=='ok'){btn.disabled=false;el.textContent=d.message||'检查失败';return;}"
"if(tag){tag.textContent='检查中';tag.style.color='#38bdf8';}"
"pollCheck();"
"});"
"}"
"function pollCheck(){"
"var n=0,btn=document.getElementById('checkBtn'),el=document.getElementById('otaCheck'),tag=document.getElementById('otaTag');"
"var timer=setInterval(function(){"
"fetch('/api/ota/status').then(function(r){return r.json();}).then(function(s){"
"n++;"
"/* check_state: 0 未检查 / 1 检查中 / 2 完成 / 3 失败 */"
"if(s.check_state===2||s.check_state===3){clearInterval(timer);btn.disabled=false;"
"if(tag&&s.state!=='success'){tag.textContent='空闲';tag.style.color='';}"
"if(s.check_state===2){"
"if(s.has_update){"
"el.innerHTML='发现新版本 <b>'+escHtml(s.latest_version)+'</b>'+"
"(s.check_url?' · <a href=\"'+escHtml(s.check_url)+'\" target=\"_blank\" rel=\"noopener\">下载</a>':'')+"
"' — 下载后拖到上方刷写';"
"showToast('发现新版本 '+s.latest_version,'');"
"}else{el.textContent=s.check_msg||'已是最新版本';}"
"}else{el.textContent=s.check_msg||'检查更新失败';}"
"}"
"}).catch(function(){});"
"if(n>12){clearInterval(timer);btn.disabled=false;el.textContent='检查超时, 请重试';}"
"},1500);"
"}"
"/* ===== 设置 / 凭据 ===== */"
"function saveSettings(){"
"var i=parseInt(document.getElementById('interval').value,10)||0;"
"var t=parseInt(document.getElementById('timeout').value,10)||0;"
"var po=document.getElementById('poweroffEnabled').checked?1:0;"
"var pc=parseInt(document.getElementById('poweroffCnt').value,10);"
"if(i<1||i>3600){showToast('心跳间隔需在 1~3600 秒之间','warn');return;}"
"if(t<60||t>86400){showToast('超时时间需在 60~86400 秒之间','warn');return;}"
"if(t<i*2){showToast('超时时间应至少为心跳间隔的 2 倍','warn');return;}"
"if(!(pc>=1&&pc<=20)){showToast('自动关机次数需在 1~20 之间','warn');return;}"
"fetch('/api/settings?interval='+i+'&timeout='+t+'&poweroff='+po+'&poweroff_cnt='+pc,{method:'POST'})"
".then(function(r){return r.json();}).then(function(d){showToast(d.message||'已保存');});"
"}"
"function resetStats(){if(confirm('确定清零心跳统计和服务器重启计数？')){fetch('/api/reset_stats',{method:'POST'}).then(function(r){return r.json();}).then(function(d){showToast(d.message||'已清零');refreshAll();});}}"
"function saveProtect(){"
"var ne=document.getElementById('notifyEnabled').checked?1:0;"
"var nu=document.getElementById('notifyUrl').value.trim();"
"var nt=document.getElementById('notifyToken').value.trim();"
"if(ne&&!nu){showToast('已启用通知，请先填写推送地址','warn');return;}"
"if(nu&&!/^https?:\\/\\//i.test(nu)){showToast('推送地址需以 http:// 或 https:// 开头','warn');return;}"
"fetch('/api/settings?poweroff='+po+'&poweroff_cnt='+pc+'&notify='+ne+'&notify_url='+encodeURIComponent(nu)+'&notify_token='+encodeURIComponent(nt),{method:'POST'})"
".then(function(r){return r.json();}).then(function(d){showToast(d.message||'已保存',d.status==='ok'?'':'error');});"
"}"
"function testNotify(){"
"fetch('/api/notify_test',{method:'POST'}).then(function(r){return r.json();}).then(function(d){showToast(d.message||'已发送',d.status==='ok'?'':'error');});"
"}"
"function changePassword(){"
"var u=document.getElementById('username').value.trim(),op=document.getElementById('old_password').value,p=document.getElementById('password').value;"
"if(p.length>0&&p.length<4){showToast('新密码至少 4 位','warn');return;}"
"fetch('/api/change_password?username='+encodeURIComponent(u)+'&old_password='+encodeURIComponent(op)+'&password='+encodeURIComponent(p),{method:'POST'})"
".then(function(r){return r.json();}).then(function(d){"
"if(d.status==='ok'){showToast(d.message||'已更新，请重新登录');setTimeout(function(){location.href='/login';},1500);}"
"else{showToast(d.message||'更新失败','error');}"
"});"
"}"
"/* ===== 电源 / 操作 ===== */"
"/* 电源键短按脉冲: 关机状态=开机, 开机状态=让系统正常关机 (同一路脉冲, 由服务器自己解释) */"
"var powerIsOn=false;"
"function powerToggle(){"
"if(powerIsOn){"
"if(!confirm('服务器当前为开机状态。\\n短按电源键让系统正常关机 (非强制断电)，随后自动暂停看门狗监控。\\n继续？'))return;"
"fetch('/api/shutdown',{method:'POST'}).then(function(r){return r.json();}).then(function(d){showToast(d.message||'已发送关机脉冲');setTimeout(function(){refreshAll();refreshPowerState();},3500);});"
"}else{"
"if(!confirm('向服务器发送开机脉冲？看门狗将恢复监控。'))return;"
"fetch('/api/poweron',{method:'POST'}).then(function(r){return r.json();}).then(function(d){showToast(d.message||'已发送');refreshAll();});"
"}"
"}"
"function rebootServer(){if(confirm('向服务器发送重启脉冲？')){fetch('/api/reboot',{method:'POST'}).then(function(r){return r.json();}).then(function(d){showToast(d.message||'已发送');});}}"
"function powerOffServer(){if(confirm('确定强制关机吗？将长按电源键 5 秒。')){fetch('/api/poweroff',{method:'POST'}).then(function(r){return r.json();}).then(function(d){showToast(d.message||'已发送');});}}"
"function resetWifi(){"
"if(confirm('清除所有配置并恢复到出厂设置？\\n设备将重启进入配网模式。')){"
"fetch('/api/reset_wifi',{method:'POST'}).then(function(r){return r.json();}).then(function(d){showToast(d.message||'正在重置...');});}"
"}"
"function clearLogs(){if(confirm('确定清空所有事件日志？此操作不可恢复。')){fetch('/api/clear_logs',{method:'POST'}).then(function(r){return r.json();}).then(function(d){showToast(d.message||'已清空');refreshLogs();});}}"
"/* ===== 状态刷新 ===== */"
"function refreshAll(){"
"fetch('/api/status').then(function(r){return r.json();}).then(function(d){"
"var led=document.getElementById('led'),st=document.getElementById('state');"
"var map={healthy:['#22c55e','系统正常 · 心跳正常'],warning:['#f59e0b','警告 · 接近超时'],down:['#ef4444','服务器宕机 · 正在重启'],idle:['#64748b','USB 已断开']};"
"var c=map[d.state_str]||map.idle;"
"led.style.background=c[0];led.style.boxShadow='0 0 0 8px '+c[0]+'22,0 0 40px '+c[0]+'55';"
"st.textContent=c[1];st.style.color=c[0];"
"led.classList.toggle('pulse',d.state_str==='healthy');"
"document.getElementById('usbDot').style.background=d.usb_connected?'#22c55e':'#ef4444';"
"document.getElementById('usbTxt').textContent=d.usb_connected?'Connected':'Disconnected';"
"if(typeof d.ip==='string'&&d.ip&&d.ip!=='-'){document.getElementById('ipTxt').textContent=d.ip;}"
"if(typeof d.rssi==='number'&&d.rssi<0){document.getElementById('rssiTxt').textContent=d.rssi+' dBm';}"
"/* 记录设备真实运行时长 (来自后端 esp_timer 计时), 供 tickUptime 本地插值 */"
"if(typeof d.uptime_s==='number'){devUptime=d.uptime_s;lastSync=Date.now();}"
"if(typeof d.wallclock_s==='number'){devWallclock=d.wallclock_s;}"
"/* 用 <small> 而非 class=\"small\": 样式规则是 .stat .value small */"
"if(typeof d.consecutive_reboots==='number'){document.getElementById('consecReboots').innerHTML=d.consecutive_reboots+'<small>次</small>';}"
"/* 看门狗已停止: 区分\"软关机暂停\"(蓝色提示) 与\"故障停止\"(红色告警) */"
"if(d.watchdog_running===false){"
"if(d.paused===true){"
"st.textContent='监控已暂停 · 服务器已关机';st.style.color='#38bdf8';"
"led.style.background='#38bdf8';led.style.boxShadow='0 0 0 8px rgba(56,189,248,.12),0 0 40px rgba(56,189,248,.3)';"
"led.classList.remove('pulse');"
"}else{"
"st.textContent='看门狗已停止 · 需管理员处理';st.style.color='#ef4444';"
"led.style.background='#ef4444';led.style.boxShadow='0 0 0 8px rgba(239,68,68,.12),0 0 40px rgba(239,68,68,.35)';"
"led.classList.remove('pulse');"
"}"
"}"
"});"
"}"
"function refreshPowerState(){"
"fetch('/api/power-state').then(function(r){return r.json();}).then(function(d){"
"var el=document.getElementById('powerState'),dt=document.getElementById('powerDot'),"
"hint=document.getElementById('powerHint'),pb=document.getElementById('powerBtn');"
"/* 电源控制按钮随状态切换: 开机 -> 显示\"关机\"; 关机/未知 -> 显示\"开机\" */"
"powerIsOn=(d.state==='on');"
"if(pb){"
"pb.textContent=powerIsOn?'\\u23fb 关机':'\\u23fb 开机';"
"pb.className=powerIsOn?'btn btn-danger btn-block':'btn btn-power btn-block';"
"}"
"if(d.state==='unknown'){"
"el.textContent='未接入检测线';el.style.color='#94a3b8';"
"dt.style.background='#475569';dt.style.boxShadow='none';"
"if(hint)hint.innerHTML='GPIO'+d.gpio+' 未检测到 PWR_LED 信号 (悬空) \\u2014 接上主板 PWR_LED 后自动生效';"
"return;"
"}"
"el.textContent=d.state==='on'?'开机':'关机';"
"el.style.color=d.state==='on'?'#22c55e':'#64748b';"
"dt.style.background=d.state==='on'?'#22c55e':'#475569';"
"dt.style.boxShadow=d.state==='on'?'0 0 12px rgba(34,197,94,.7)':'none';"
"if(hint)hint.innerHTML='通过 PWR_LED (GPIO'+d.gpio+') 检测，每 3 秒刷新';"
"});"
"}"
"function escHtml(s){var d={'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'};"
"return String(s).replace(/[&<>\"']/g,function(c){return d[c];});}"
"function refreshLogs(){"
"fetch('/api/logs').then(function(r){return r.json();}).then(function(d){"
"var el=document.getElementById('log');"
"if(!d.entries||!d.entries.length){el.innerHTML='<div>暂无日志</div>';return;}"
"el.innerHTML=d.entries.slice().reverse().map(function(e){"
"var cls=e.level>=2?'l-error':e.level>=1?'l-warn':'l-info';"
"/* 后端输出字段为 message (见 web_server.c handler_logs)。"
"   兼容旧版 msg, 并在都缺失时显示占位符, 避免整列 undefined。 */"
"var text=(typeof e.message==='string'&&e.message)?e.message"
":((typeof e.msg==='string'&&e.msg)?e.msg:'(无内容)');"
"/* 用 innerHTML 渲染, 必须先转义: 日志含 WiFi SSID 等用户输入,"
"   若带 < > & 会破坏页面结构。后端虽已做 JSON 转义, 但 JSON.parse"
"   会把 \\u003c 还原成 <, 这一层的转义不可省。 */"
"return '<div class=\"'+cls+'\">['+escHtml(e.time)+'] '+escHtml(text)+'</div>';"
"}).join('');"
"});"
"}"
"/* ===== 运行时间: 后端 uptime_s + 本地每秒插值 ===== */"
"var devUptime=-1,lastSync=0,devWallclock=0;"
"function fmtDevClock(wc){"
"if(!wc||wc<1609459200)return '';"
"var t=new Date(wc*1000);var p=function(n){return (n<10?'0':'')+n;};"
"return t.getFullYear()+'-'+p(t.getMonth()+1)+'-'+p(t.getDate())+' · '+p(t.getHours())+':'+p(t.getMinutes())+':'+p(t.getSeconds())+' · ';"
"}"
"function tickUptime(){"
"if(devUptime<0)return;"
"var s=devUptime+Math.floor((Date.now()-lastSync)/1000);"
"var d=Math.floor(s/86400),h=Math.floor((s%86400)/3600),m=Math.floor((s%3600)/60),sec=s%60;"
"document.getElementById('uptime').textContent=fmtDevClock(devWallclock)+'已运行 '+(d>0?d+'d ':'')+h+'h '+m+'m '+sec+'s';"
"}"
"setInterval(refreshAll,5000);"
"setInterval(refreshPowerState,3000);"
"setInterval(refreshLogs,4000);"
"setInterval(tickUptime,1000);"
"refreshAll();refreshPowerState();refreshLogs();tickUptime();"
"</script>"
"</body>"
"</html>";

const char *dashboard_get_html(void)
{
    return s_html;
}
