/**
 * @file dashboard_html.c
 * @brief 美化后的 Web 控制台 HTML (深色玻璃拟态主题)
 *
 * 页面结构:
 *   - 顶栏: 品牌 + 版本 + 运行时间 + 退出登录
 *   - 状态卡: 脉冲动画 LED + 状态文案 + USB/分区/固件版本
 *   - 统计卡: 心跳 / 响应 / 超时 + 服务器重启次数
 *   - 固件更新 (OTA): 拖拽 / 点击上传 .bin, 校验, 进度条, 刷写详情, 自动重启
 *   - 参数设置 / 修改凭据 / 操作 / 电源状态 / 实时事件日志
 *
 * 通过 dashboard_get_html() 返回模板字符串, 动态值以双花括号占位符表示。
 * 刻意不用 printf 格式符: CSS 中大量百分号 (如 width:100%) 经 snprintf
 * 消费会触发 -Wformat 错误甚至运行时越界, 改用占位符彻底规避。
 */

#include <stdio.h>
#include "dashboard_html.h"

static const char *s_html =
"<!DOCTYPE html>"
"<html lang=\"zh-CN\">"
"<head>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
"<meta name=\"color-scheme\" content=\"dark\">"
"<title>看门狗控制台 · ESP32-C3</title>"
"<style>"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",\"Microsoft YaHei\",sans-serif;"
"background:radial-gradient(circle at 20% 0%,#1e1b4b 0,transparent 40%),"
"radial-gradient(circle at 80% 100%,#0c4a6e 0,transparent 40%),#0f172a;"
"color:#e2e8f0;min-height:100vh;padding:20px;padding-bottom:60px}"
".wrap{max-width:1040px;margin:0 auto}"
"/* 顶栏 */"
".topbar{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px;flex-wrap:wrap;gap:12px}"
".brand{display:flex;align-items:center;gap:14px}"
".logo{width:46px;height:46px;border-radius:13px;background:linear-gradient(135deg,#38bdf8,#6366f1);"
"display:flex;align-items:center;justify-content:center;font-weight:800;font-size:22px;color:#0f172a;"
"box-shadow:0 6px 20px rgba(99,102,241,.4)}"
".brand h1{font-size:19px;color:#f1f5f9;letter-spacing:.5px}"
".brand .ver{font-size:12px;color:#64748b;margin-top:2px}"
".topright{display:flex;align-items:center;gap:10px;font-size:13px;color:#94a3b8}"
".uptime{background:rgba(255,255,255,.05);padding:7px 13px;border-radius:20px;border:1px solid rgba(255,255,255,.08)}"
".btn-logout{color:#94a3b8;text-decoration:none;padding:7px 14px;border-radius:9px;"
"background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.08);transition:.2s}"
".btn-logout:hover{color:#fff;background:rgba(239,68,68,.25);border-color:#ef4444}"
"/* 网格 */"
".grid{display:grid;grid-template-columns:1.4fr 1fr;gap:18px;margin-bottom:18px}"
".grid3{grid-template-columns:1.4fr 1fr .9fr}"
".grid3 .panel{margin-bottom:0}"
"@media(max-width:820px){.grid,.grid3{grid-template-columns:1fr}}"
".card{background:rgba(30,41,59,.72);backdrop-filter:blur(12px);border:1px solid rgba(255,255,255,.08);"
"border-radius:18px;padding:24px}"
".card h2{font-size:14px;color:#94a3b8;font-weight:600;margin-bottom:16px;display:flex;align-items:center;gap:8px;letter-spacing:.5px}"
".card h2 .bar{width:4px;height:16px;border-radius:3px;background:#38bdf8}"
"/* 状态 */"
".status{display:flex;align-items:center;gap:22px}"
".led-wrap{position:relative;flex-shrink:0}"
".led{width:92px;height:92px;border-radius:50%;background:#64748b;"
"box-shadow:0 0 0 8px rgba(100,116,139,.12),0 0 40px rgba(100,116,139,.35);transition:all .6s}"
".led.pulse{animation:pulse 2s infinite}"
"@keyframes pulse{0%{box-shadow:0 0 0 0 rgba(34,197,94,.45)}70%{box-shadow:0 0 0 16px rgba(34,197,94,0)}100%{box-shadow:0 0 0 0 rgba(34,197,94,0)}}"
".state-block{flex:1}"
".state{font-size:26px;font-weight:800;color:#64748b;transition:color .4s}"
".subinfo{margin-top:12px;display:flex;flex-direction:column;gap:7px;font-size:13px;color:#94a3b8}"
".subinfo span{display:flex;align-items:center;gap:8px}"
".dot{width:8px;height:8px;border-radius:50%;background:#64748b;display:inline-block}"
"/* 统计 */"
".stats{display:grid;grid-template-columns:1fr 1fr;gap:12px}"
".stat{background:rgba(15,23,42,.6);border:1px solid rgba(255,255,255,.06);border-radius:13px;padding:16px}"
".stat .label{font-size:12px;color:#64748b;margin-bottom:6px}"
".stat .value{font-size:28px;font-weight:800;color:#38bdf8}"
".stat .value small{font-size:12px;color:#64748b;font-weight:500;margin-left:3px}"
".stat.full{grid-column:1/-1}"
"/* 通用面板 */"
".panel{background:rgba(30,41,59,.72);backdrop-filter:blur(12px);border:1px solid rgba(255,255,255,.08);"
"border-radius:18px;padding:24px;margin-bottom:18px}"
".panel h3{font-size:15px;color:#f1f5f9;margin-bottom:16px;display:flex;align-items:center;gap:8px}"
".panel h3 .bar{width:4px;height:18px;border-radius:3px;background:#38bdf8}"
".panel h3 .tag{margin-left:auto;font-size:11px;color:#64748b;font-weight:400;background:rgba(255,255,255,.05);"
"padding:3px 9px;border-radius:6px}"
"label{display:block;font-size:12px;color:#94a3b8;margin:12px 0 6px}"
"input{width:100%;padding:12px 13px;border:1px solid #334155;border-radius:10px;background:#0f172a;color:#e2e8f0;"
"font-size:14px;transition:border .2s}"
"input:focus{outline:none;border-color:#38bdf8}"
"/* 按钮 */"
".btn{width:auto;min-width:150px;padding:12px 26px;border:none;border-radius:10px;font-size:14px;font-weight:700;cursor:pointer;"
"transition:transform .1s,opacity .2s,filter .2s;margin-top:10px}"
".btn:active{transform:scale(.98)}"
".btn:disabled{opacity:.45;cursor:not-allowed;filter:grayscale(.5)}"
".btn-primary{background:linear-gradient(135deg,#38bdf8,#0ea5e9);color:#0f172a}"
".btn-power{background:linear-gradient(135deg,#22c55e,#16a34a);color:#fff}"
".btn-danger{background:linear-gradient(135deg,#ef4444,#dc2626);color:#fff}"
".btn-secondary{background:#475569;color:#fff}"
".btn-secondary:hover{background:#334155}"
".row2{display:flex;flex-wrap:wrap;gap:10px}"
".row2 .btn{margin-top:0}"
"/* OTA 上传 */"
".drop{border:2px dashed #334155;border-radius:14px;padding:18px 16px;text-align:center;cursor:pointer;"
"transition:all .25s;position:relative;background:rgba(15,23,42,.4)}"
".drop:hover,.drop.drag{border-color:#38bdf8;background:rgba(56,189,248,.07)}"
".drop.hasfile{border-color:#22c55e;border-style:solid;background:rgba(34,197,94,.07)}"
".drop .ic{font-size:24px;margin-bottom:6px;display:block}"
".drop p{color:#94a3b8;font-size:13px;line-height:1.6}"
".drop .file{color:#38bdf8;font-weight:600}"
".drop input[type=file]{position:absolute;inset:0;opacity:0;cursor:pointer}"
".meta{display:flex;gap:10px;margin-top:14px;flex-wrap:wrap}"
".meta div{flex:1;min-width:90px;background:rgba(15,23,42,.6);border:1px solid rgba(255,255,255,.06);"
"border-radius:10px;padding:10px 12px}"
".meta .k{font-size:11px;color:#64748b}"
".meta .v{font-size:14px;font-weight:700;color:#e2e8f0;margin-top:2px;word-break:break-all}"
".progress{height:10px;background:#0f172a;border-radius:6px;margin-top:16px;overflow:hidden;display:none}"
".progress .bar{height:100%;width:0;background:linear-gradient(90deg,#38bdf8,#6366f1);transition:width .3s}"
".hint{font-size:12px;color:#64748b;margin-top:12px;line-height:1.7}"
".ok{color:#22c55e}.warn{color:#f59e0b}.err{color:#ef4444}"
"/* Toast */"
"#toast{position:fixed;bottom:24px;left:50%;transform:translateX(-50%) translateY(24px);"
"background:#22c55e;color:#fff;padding:14px 26px;border-radius:12px;font-size:14px;font-weight:600;"
"opacity:0;transition:all .35s;z-index:999;box-shadow:0 12px 40px rgba(0,0,0,.35);max-width:90%;text-align:center}"
"#toast.active{opacity:1;transform:translateX(-50%) translateY(0)}"
"#toast.error{background:#ef4444}"
"#toast.warn{background:#f59e0b;color:#0f172a}"
"/* 电源 */"
".power{font-size:22px;font-weight:800;margin-top:6px}"
".log{max-height:220px;overflow-y:auto;font-family:'SF Mono',Consolas,monospace;font-size:12px;"
"background:rgba(15,23,42,.7);border-radius:11px;padding:12px;border:1px solid rgba(255,255,255,.06)}"
".log div{padding:2px 0;color:#cbd5e1;border-bottom:1px solid rgba(255,255,255,.04)}"
".log .l-warn{color:#f59e0b}.log .l-error{color:#ef4444}.log .l-info{color:#38bdf8}"
".log::-webkit-scrollbar{width:6px}"
".log::-webkit-scrollbar-thumb{background:#334155;border-radius:3px}"
"@media(max-width:640px){.stats{grid-template-columns:1fr}}"
"</style>"
"</head>"
"<body>"
"<div class=\"wrap\">"
"<div class=\"topbar\">"
"<div class=\"brand\">"
"<div class=\"logo\">W</div>"
"<div>"
"<h1>看门狗控制台</h1>"
"<div class=\"ver\">固件版本 · v{{VERSION}} · 构建日期 {{BUILD_DATE}}</div>"
"</div>"
"</div>"
"<div class=\"topright\">"
"<span class=\"uptime\" id=\"uptime\">运行中...</span>"
"<a class=\"btn-logout\" href=\"/logout\">退出</a>"
"</div>"
"</div>"
"<!-- 状态 + 统计 + 电源 -->"
"<div class=\"grid grid3\">"
"<div class=\"card\">"
"<h2><span class=\"bar\"></span>服务器状态</h2>"
"<div class=\"status\">"
"<div class=\"led-wrap\"><div class=\"led {{LED_CLASS}}\" id=\"led\" style=\"background:{{LED_COLOR}}\"></div></div>"
"<div class=\"state-block\">"
"<div class=\"state\" id=\"state\">{{STATE_TEXT}}</div>"
"<div class=\"subinfo\">"
"<span><i class=\"dot\" id=\"usbDot\"></i> USB CDC: <b id=\"usbTxt\">{{USB_STATE}}</b></span>"
"<span><i class=\"dot\"></i> 心跳间隔 <b>{{INTERVAL}} s</b> · 超时 <b>{{TIMEOUT}} s</b></span>"
"<span><i class=\"dot\"></i> 固件: <b>{{VERSION}}</b> · 分区: <b>{{PARTITION}}</b></span>"
"</div>"
"</div>"
"</div>"
"</div>"
"<div class=\"card\">"
"<h2><span class=\"bar\"></span>心跳统计</h2>"
"<div class=\"stats\">"
"<div class=\"stat\"><div class=\"label\">心跳数</div><div class=\"value\">{{HB_COUNT}}<span class=\"small\">次</span></div></div>"
"<div class=\"stat\"><div class=\"label\">响应数</div><div class=\"value\">{{RESP_COUNT}}<span class=\"small\">次</span></div></div>"
"<div class=\"stat\"><div class=\"label\">超时数</div><div class=\"value\">{{TIMEOUT_COUNT}}<span class=\"small\">次</span></div></div>"
"<div class=\"stat\"><div class=\"label\">服务器已重启</div><div class=\"value\">{{REBOOT_COUNT}}<span class=\"small\">次</span></div></div>"
"</div>"
"</div>"
"<!-- 服务器电源状态 -->"
"<div class=\"panel\">"
"<h3><span class=\"bar\"></span>服务器电源状态</h3>"
"<div class=\"power\" id=\"powerState\">检测中...</div>"
"<div class=\"hint\">通过 PWR_LED (GPIO7) 检测，每 3 秒刷新</div>"
"</div>"
"</div>"
"<!-- 固件更新 OTA -->"
"<div class=\"panel\">"
"<h3><span class=\"bar\"></span>固件更新 (OTA)<span class=\"tag\" id=\"otaTag\">空闲</span></h3>"
"<div class=\"drop\" id=\"drop\">"
"<span class=\"ic\">📦</span>"
"<p>拖拽 .bin 固件到此处，或 <span class=\"file\">点击选择文件</span></p>"
"<input type=\"file\" id=\"firmware\" accept=\".bin,.hex,application/octet-stream\">"
"</div>"
"<div class=\"meta\" id=\"meta\" style=\"display:none\">"
"<div><div class=\"k\">文件名</div><div class=\"v\" id=\"mName\">-</div></div>"
"<div><div class=\"k\">大小</div><div class=\"v\" id=\"mSize\">-</div></div>"
"<div><div class=\"k\">固件版本</div><div class=\"v\" id=\"mVer\">上传后解析</div></div>"
"</div>"
"<div class=\"progress\" id=\"progress\"><div class=\"bar\" id=\"bar\"></div></div>"
"<div class=\"hint\" id=\"otaHint\">支持: <span class=\"ok\">.bin (ESP32-C3 分区镜像)</span>。前端以二进制流上传，后端流式写入 OTA 分区。"
"流程: <span><b>选择文件 → 校验镜像头 → 写入 Flash → 切换启动分区 → 自动重启</b></span>。"
"升级期间请勿断电；新固件若启动失败将自动回滚上一版本。</div>"
"<div class=\"row2\">"
"<button class=\"btn btn-primary\" id=\"uploadBtn\" onclick=\"uploadFirmware()\" disabled>上传并刷写固件</button>"
"<button class=\"btn btn-secondary\" id=\"rebootBtn\" onclick=\"rebootDevice()\" style=\"display:none\">立即重启设备</button>"
"</div>"
"</div>"
"<!-- 参数 + 凭据 -->"
"<div class=\"grid\">"
"<div class=\"panel\">"
"<h3><span class=\"bar\"></span>看门狗参数</h3>"
"<label>心跳间隔 (秒) — 每 N 秒发送一次</label>"
"<input type=\"number\" id=\"interval\" value=\"{{INTERVAL}}\" min=\"1\">"
"<label>超时时间 (秒) — 超过则判定服务器宕机</label>"
"<input type=\"number\" id=\"timeout\" value=\"{{TIMEOUT}}\" min=\"60\">"
"<button class=\"btn btn-primary\" onclick=\"saveSettings()\">保存设置</button>"
"</div>"
"<div class=\"panel\">"
"<h3><span class=\"bar\"></span>登录凭据</h3>"
"<label>新用户名 (留空则不修改)</label>"
"<input type=\"text\" id=\"username\" placeholder=\"admin\">"
"<label>当前密码 <span class=\"err\">*</span></label>"
"<input type=\"password\" id=\"old_password\" placeholder=\"验证身份\">"
"<label>新密码 (至少 4 位)</label>"
"<input type=\"password\" id=\"password\" placeholder=\"••••••••\">"
"<button class=\"btn btn-primary\" onclick=\"changePassword()\">更新用户名 / 密码</button>"
"</div>"
"</div>"
"<!-- 操作 -->"
"<div class=\"panel\">"
"<h3><span class=\"bar\"></span>服务器电源控制</h3>"
"<div class=\"row2\">"
"<button class=\"btn btn-power\" onclick=\"powerOnServer()\">开机（关机）</button>"
"<button class=\"btn btn-danger\" onclick=\"powerOffServer()\">⏹ 强制关机 (长按 5s)</button>"
"<button class=\"btn btn-danger\" onclick=\"rebootServer()\">重启服务器</button>"
"<button class=\"btn btn-secondary\" onclick=\"resetWifi()\">重置网络 / 恢复默认</button>"
"</div>"
"</div>"
"<!-- 实时事件日志 -->"
"<div class=\"panel\">"
"<h3><span class=\"bar\"></span>实时事件日志</h3>"
"<div class=\"log\" id=\"log\">加载中...</div>"
"</div>"
"</div>"
"<div id=\"toast\"></div>"
"<script>"
"var selectedFile=null,otaDone=false;"
"function showToast(msg,type){"
"var t=document.getElementById('toast');"
"t.textContent=msg;t.className=(type==='error'?'active error':type==='warn'?'active warn':'active');"
"setTimeout(function(){t.className='';},4000);"
"}"
"/* 文件选择 */"
"var drop=document.getElementById('drop'),fi=document.getElementById('firmware'),"
"up=document.getElementById('uploadBtn'),meta=document.getElementById('meta');"
"function pickFile(file){"
"selectedFile=file;"
"if(!file)return;"
"if(!/\\.bin$/i.test(file.name)&&file.type!=='application/octet-stream'){"
"showToast('请选择 .bin 固件文件','error');selectedFile=null;return;"
"}"
"var kb=Math.round(file.size/1024);"
"drop.querySelector('p').innerHTML='已选择: <span class=\"file\">'+file.name+'</span> ('+kb+' KB)';"
"drop.classList.add('hasfile');"
"meta.style.display='flex';"
"document.getElementById('mName').textContent=file.name;"
"document.getElementById('mSize').textContent=kb+' KB';"
"document.getElementById('mVer').textContent='待校验';"
"up.disabled=false;"
"}"
"fi.addEventListener('change',function(e){pickFile(e.target.files[0]);});"
"['dragenter','dragover'].forEach(function(ev){drop.addEventListener(ev,function(e){e.preventDefault();drop.classList.add('drag');});});"
"['dragleave','drop'].forEach(function(ev){drop.addEventListener(ev,function(e){e.preventDefault();drop.classList.remove('drag');});});"
"drop.addEventListener('drop',function(e){if(e.dataTransfer.files.length)pickFile(e.dataTransfer.files[0]);});"
"/* 解析上传镜像中的固件版本 (esp_app_desc_t 在镜像头部固定偏移) */"
"function readVersion(file){"
"var slice=file.slice(0,2048);var fr=new FileReader();"
"fr.onload=function(e){"
"var b=new Uint8Array(e.target.result);"
"var el=document.getElementById('mVer');"
"/* ESP32 镜像头 (24 字节, v4.3+) + 第1段头 (8 字节) => esp_app_desc 自偏移 32 起 */"
"if(b.length<80||b[0]!==0xe9){el.textContent='非标准镜像';return;}"
"/* esp_app_desc_t: magic_word(4)=0xABCD5432 @32, version[32]@+16 (即镜像偏移 48) */"
"var dm=(b[32]|(b[33]<<8)|(b[34]<<16)|(b[35]<<24))>>>0;"
"if(dm!==0xABCD5432){el.textContent='未知 (无应用描述)';return;}"
"var v='';for(var i=48;i<80&&b[i];i++)v+=String.fromCharCode(b[i]);"
"el.textContent=v||'未知';"
"};"
"fr.readAsArrayBuffer(slice);"
"}"
"fi.addEventListener('change',function(e){if(e.target.files[0])readVersion(e.target.files[0]);});"
"/* 上传固件 (XHR + 进度) */"
"function uploadFirmware(){"
"if(!selectedFile){showToast('请先选择固件文件','warn');return;}"
"if(!confirm('确定刷写固件吗？过程请勿断电。'))return;"
"var xhr=new XMLHttpRequest();"
"xhr.open('POST','/api/firmware');"
"xhr.setRequestHeader('Content-Type','application/octet-stream');"
"var prog=document.getElementById('progress'),bar=document.getElementById('bar'),tag=document.getElementById('otaTag');"
"prog.style.display='block';up.disabled=true;otaDone=false;"
"tag.textContent='上传中';tag.style.color='#38bdf8';"
"xhr.upload.onprogress=function(e){if(e.lengthComputable){var p=Math.round(e.loaded*100/e.total);bar.style.width=p+'%';}};"
"xhr.onload=function(){"
"try{var resp=JSON.parse(xhr.responseText);"
"if(resp.status==='ok'){"
"bar.style.width='100%';tag.textContent='写入中';tag.style.color='#f59e0b';"
"showToast('文件已上传，正在写入 Flash...', '');"
"pollOtaStatus();"
"}else{"
"tag.textContent='失败';tag.style.color='#ef4444';"
"showToast((resp.message||'刷写失败')+' (code '+(resp.code||'')+')','error');up.disabled=false;"
"}"
"}catch(err){showToast('服务器无响应，可能正在重启', '');setTimeout(function(){location.reload();},3000);}"
"};"
"function pollOtaStatus(){"
"var timer=setInterval(function(){"
"fetch('/api/ota/status').then(function(r){return r.json();}).then(function(s){"
"if(s.state==='writing'){bar.style.width=s.progress+'%';}"
"else if(s.state==='success'){"
"otaDone=true;clearInterval(timer);bar.style.width='100%';"
"tag.textContent='成功 · 待重启';tag.style.color='#22c55e';"
"showToast('刷写成功，设备即将重启 (约 3 秒)...', '');"
"document.getElementById('rebootBtn').style.display='block';"
"setTimeout(function(){location.reload();},4000);"
"}else if(s.state==='failed'){"
"otaDone=true;clearInterval(timer);tag.textContent='失败';tag.style.color='#ef4444';"
"showToast('写入失败，请重试','error');up.disabled=false;"
"}"
"}).catch(function(){if(!otaDone){clearInterval(timer);setTimeout(pollOtaStatus,1500);}});"
"},1000);"
"}"
"xhr.onerror=function(){showToast('网络错误，请重试','error');up.disabled=false;};"
"xhr.send(selectedFile);"
"}"
"function rebootDevice(){if(confirm('立即重启设备？'))fetch('/api/reboot',{method:'POST'}).then(function(r){return r.json();}).then(function(d){showToast(d.message||'已重启');});}"
"/* 设置 / 凭据 */"
"function saveSettings(){"
"var i=document.getElementById('interval').value,t=document.getElementById('timeout').value;"
"fetch('/api/settings?interval='+i+'&timeout='+t,{method:'POST'})"
".then(function(r){return r.json();}).then(function(d){showToast(d.message||'已保存');});"
"}"
"function changePassword(){"
"var u=document.getElementById('username').value.trim(),op=document.getElementById('old_password').value,p=document.getElementById('password').value;"
"if(p.length>0&&p.length<4){showToast('新密码至少 4 位','warn');return;}"
"fetch('/api/change_password?username='+encodeURIComponent(u)+'&old_password='+encodeURIComponent(op)+'&password='+encodeURIComponent(p),{method:'POST'})"
".then(function(r){return r.json();}).then(function(d){"
"if(d.status==='ok'){showToast(d.message||'已更新，请重新登录');setTimeout(function(){location.href='/login';},1500);}"
"else{showToast(d.message||'更新失败','error');}"
"});"
"}"
"/* 电源 / 操作 */"
"function powerOnServer(){if(confirm('向服务器发送开机信号？')){fetch('/api/poweron',{method:'POST'}).then(function(r){return r.json();}).then(function(d){showToast(d.message||'已发送');});}}"
"function rebootServer(){if(confirm('向服务器发送重启脉冲？')){fetch('/api/reboot',{method:'POST'}).then(function(r){return r.json();}).then(function(d){showToast(d.message||'已发送');});}}"
"function resetWifi(){"
"if(confirm('清除 WiFi 配置并恢复默认账号密码？\\n设备将重启进入配网模式。')){"
"fetch('/api/reset_wifi',{method:'POST'}).then(function(r){return r.json();}).then(function(d){showToast(d.message||'正在重置...');});}"
"}"
"function powerOffServer(){if(confirm('确定强制关机吗？将长按电源键 5 秒。')){fetch('/api/poweroff',{method:'POST'}).then(function(r){return r.json();}).then(function(d){showToast(d.message||'已发送');});}}"
"/* 状态刷新 */"
"function refreshAll(){"
"fetch('/api/status').then(function(r){return r.json();}).then(function(d){"
"var led=document.getElementById('led'),st=document.getElementById('state');"
"var map={healthy:['#22c55e','系统正常 · 心跳正常'],warning:['#f59e0b','警告 · 接近超时'],down:['#ef4444','服务器宕机 · 正在重启'],idle:['#64748b','USB 已断开']};"
"var c=map[d.state_str]||map.idle;"
"led.style.background=c[0];led.style.boxShadow='0 0 0 8px '+c[0]+'22,0 0 40px '+c[0]+'55';"
"st.textContent=c[1];st.style.color=c[0];"
"led.classList.toggle('pulse',d.state_str==='healthy');"
"document.getElementById('usbDot').style.background=d.usb_connected?'#22c55e':'#ef4444';"
"document.getElementById('usbTxt').textContent=d.usb_connected?'Connected':'Disconnected';"
"/* 记录设备真实运行时长 (来自后端 esp_timer 计时), 供 tickUptime 本地插值 */"
"if(typeof d.uptime_s==='number'){devUptime=d.uptime_s;lastSync=Date.now();}"
"});"
"}"
"function refreshPowerState(){"
"fetch('/api/power-state').then(function(r){return r.json();}).then(function(d){"
"var el=document.getElementById('powerState');"
"el.textContent=d.state==='on'?'🟢 开机':'⚫ 关机';el.style.color=d.state==='on'?'#22c55e':'#64748b';"
"});"
"}"
"function escHtml(s){var d={'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'};"
"return String(s).replace(/[&<>\"']/g,function(c){return d[c];});}"
"function refreshLogs(){"
"fetch('/api/logs').then(function(r){return r.json();}).then(function(d){"
"var el=document.getElementById('log');"
"if(!d.entries||!d.entries.length){el.innerHTML='<div>暂无日志</div>';return;}"
"el.innerHTML=d.entries.slice().reverse().map(function(e){"
"var cls=e.level>=2?'l-error':e.level>=1?'l-warn':'l-info';"
"/* 后端输出字段为 message (见 web_server.c handler_logs)。"
"   兼容旧版 msg, 并在都缺失时显示占位符, 避免整列 undefined。 */"
"var text=(typeof e.message==='string'&&e.message)?e.message"
":((typeof e.msg==='string'&&e.msg)?e.msg:'(无内容)');"
"/* 用 innerHTML 渲染, 必须先转义: 日志含 WiFi SSID 等用户输入,"
"   若带 < > & 会破坏页面结构。后端虽已做 JSON 转义, 但 JSON.parse"
"   会把 \\u003c 还原成 <, 这一层的转义不可省。 */"
"return '<div class=\"'+cls+'\">['+escHtml(e.time)+'] '+escHtml(text)+'</div>';"
"}).join('');"
"});"
"}"
"/* 运行时间: 显示看门狗设备真实运行时长 (后端 uptime_s + 本地每秒插值) */"
"var devUptime=-1,lastSync=0;"
"function tickUptime(){"
"if(devUptime<0)return;"
"var s=devUptime+Math.floor((Date.now()-lastSync)/1000);"
"var d=Math.floor(s/86400),h=Math.floor((s%86400)/3600),m=Math.floor((s%3600)/60),sec=s%60;"
"document.getElementById('uptime').textContent='已运行 '+(d>0?d+'d ':'')+h+'h '+m+'m '+sec+'s';"
"}"
"setInterval(refreshAll,5000);"
"setInterval(refreshPowerState,3000);"
"setInterval(refreshLogs,4000);"
"setInterval(tickUptime,1000);"
"refreshAll();refreshPowerState();refreshLogs();tickUptime();"
"</script>"
"</body>"
"</html>";

const char *dashboard_get_html(void)
{
    return s_html;
}
