/**
 * @file wizard_html.c
 * @brief 配网向导 HTML 页面 (深色玻璃拟态主题, 与控制台统一)
 *
 * 设计原则：
 *  - 纯静态 HTML，单个 <form> POST 提交
 *  - 不依赖 JS 扫描、不依赖 AJAX 复杂解析
 *  - 提交后用 httpd_query_key_value 解析表单字段（最稳定）
 *  - 纯静态字符串, 不经 snprintf, 因此 CSS 中的百分号无需转义
 */

#include <stdio.h>
#include "wizard.html.h"

static const char *s_html =
        "<!DOCTYPE html>"
        "<html lang=\"zh-CN\">"
        "<head>"
        "<meta charset=\"UTF-8\">"
        "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
        "<title>WiFi 配网 · 看门狗控制台</title>"
        "<style>"
        "*{box-sizing:border-box;margin:0;padding:0}"
        "body{font-family:-apple-system,\"Microsoft YaHei\",sans-serif;"
        "background:radial-gradient(circle at 50% 15%,#1e1b4b 0,transparent 45%),#0f172a;"
        "color:#e2e8f0;min-height:100vh;display:flex;align-items:center;justify-content:center;padding:20px}"
        ".container{width:100%;max-width:420px;background:rgba(30,41,59,.9);backdrop-filter:blur(12px);"
        "border:1px solid rgba(255,255,255,.08);border-radius:22px;padding:34px;box-shadow:0 24px 60px rgba(0,0,0,.4)}"
        ".logo{width:52px;height:52px;margin:0 auto 18px;border-radius:15px;background:linear-gradient(135deg,#38bdf8,#6366f1);"
        "display:flex;align-items:center;justify-content:center;font-weight:800;font-size:24px;color:#0f172a}"
        "h1{color:#f1f5f9;text-align:center;font-size:20px;margin-bottom:6px}"
        ".sub{text-align:center;color:#64748b;font-size:13px;margin-bottom:26px}"
        "label{display:block;font-size:13px;color:#94a3b8;margin:14px 0 6px}"
        "input{width:100%;padding:13px 14px;border:1px solid #334155;border-radius:11px;background:#0f172a;color:#e2e8f0;"
        "font-size:15px;transition:border .2s;box-sizing:border-box}"
        "input:focus{outline:none;border-color:#38bdf8}"
        "button{width:100%;padding:14px;border:none;border-radius:11px;background:linear-gradient(135deg,#38bdf8,#0ea5e9);"
        "color:#0f172a;font-size:16px;font-weight:700;cursor:pointer;margin-top:22px;transition:opacity .2s}"
        "button:hover{opacity:.9}"
        ".msg{margin-top:16px;padding:12px;border-radius:10px;text-align:center;font-size:13px;display:none}"
        ".msg.ok{display:block;background:#22c55e;color:#fff}"
        ".msg.err{display:block;background:#ef4444;color:#fff}"
        ".tip{margin-top:22px;padding:14px;background:rgba(15,23,42,.6);border:1px solid rgba(255,255,255,.06);"
        "border-radius:11px;font-size:12px;color:#94a3b8;line-height:1.7}"
        ".tip b{color:#e2e8f0}"
        ".steps{margin-top:16px;display:flex;flex-direction:column;gap:10px;font-size:13px;color:#94a3b8}"
        ".steps div{display:flex;align-items:center;gap:10px}"
        ".steps i{width:24px;height:24px;border-radius:50%;background:#38bdf8;color:#0f172a;font-weight:700;"
        "display:flex;align-items:center;justify-content:center;font-size:13px;flex-shrink:0}"
        "</style>"
        "</head>"
        "<body>"
        "<div class=\"container\">"
        "<div class=\"logo\">W</div>"
        "<h1>WiFi 配网</h1>"
        "<p class=\"sub\">ESP32-C3 USB Watchdog</p>"
        "<form id=\"f\" method=\"POST\" action=\"/connect\">"
        "<label for=\"ssid\">WiFi 名称 (SSID)</label>"
        "<input id=\"ssid\" name=\"ssid\" type=\"text\" placeholder=\"输入你的 WiFi 名称\" required maxlength=\"32\">"
        "<label for=\"password\">WiFi 密码</label>"
        "<input id=\"password\" name=\"password\" type=\"password\" placeholder=\"输入 WiFi 密码 (留空=无密码)\" maxlength=\"64\">"
        "<button type=\"submit\">保存并连接</button>"
        "</form>"
        "<div id=\"msg\" class=\"msg\"></div>"
        "<div class=\"steps\">"
        "<div><i>1</i><span>设备保存配置并重启</span></div>"
        "<div><i>2</i><span>自动连接该 WiFi</span></div>"
        "<div><i>3</i><span>浏览器访问设备 IP 进入控制台</span></div>"
        "</div>"
        "<div class=\"tip\">"
        "默认账号: <b>admin</b> / <b>admin123</b><br>"
        "如需重新配网，长按复位按钮 5 秒即可。<br>"
        "重置网络会同时恢复默认账号密码。"
        "</div>"
        "</div>"
        "<script>"
        "var f=document.getElementById('f');"
        "var msg=document.getElementById('msg');"
        "f.addEventListener('submit',function(e){"
        "e.preventDefault();"
        "var ssid=document.getElementById('ssid').value.trim();"
        "var password=document.getElementById('password').value;"
        "if(ssid.length===0){"
        "msg.className='msg err';"
        "msg.textContent='请填写 WiFi 名称';"
        "return;"
        "}"
        "var data='ssid='+encodeURIComponent(ssid)+'&password='+encodeURIComponent(password);"
        "fetch('/connect',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:data})"
        ".then(function(r){return r.json();})"
        ".then(function(d){"
        "if(d.status==='ok'){"
        "msg.className='msg ok';"
        "msg.textContent=d.message||'已保存，设备即将重启...';"
        "}else{"
        "msg.className='msg err';"
        "msg.textContent=d.message||'保存失败';"
        "}"
        "})"
        ".catch(function(){"
        "msg.className='msg err';"
        "msg.textContent='请求失败，请重试';"
        "});"
        "});"
        "</script>"
        "</body>"
        "</html>"
;

const char *wizard_get_html(void)
{
    return s_html;
}
